#Login
InputUserName       = "//input[@id='user-name']"
InputPassword       = "//input[@id='password']"
btnLogin            = "//input[@id='login-button']"
errorMessage        = "//div[@class='error-message-container error']"
closeErrorMessage   = "//button[@class='error-button']//*[name()='svg']"
brgrMenu            = "//button[@id='react-burger-menu-btn']"
logout              = "//a[@id='logout_sidebar_link']"
HeaderLogin         = "//div[@id='header_container']"
loginLogo           = "//div[@class='login_logo']"
clearUsername       = "//div[@class='login-box']//div[1]//*[name()='svg']"